/**
 * Generates DIRECTORY.md and DIRECTORY.html with a screenshot and description
 * of each app.
 *
 * Usage: npm run directory
 *
 * For each app in apps/:
 *   1. Visits the app in a browser
 *   2. Takes a screenshot → apps/<name>/screenshot.png
 *   3. Reads <title> and <meta name="description"> from the page
 *   4. Writes DIRECTORY.md (for GitHub) and DIRECTORY.html (for local browsing)
 */

import { test } from "@playwright/test";
import * as fs from "fs";
import * as path from "path";

const ROOT = path.resolve(__dirname, "..");
const APPS_DIR = path.join(ROOT, "apps");

interface AppEntry {
  name: string;
  title: string;
  description: string;
  screenshot: string;
}

test("generate app directory", async ({ page }) => {
  const appDirs = fs
    .readdirSync(APPS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory() && fs.existsSync(path.join(APPS_DIR, d.name, "index.html")))
    .map((d) => d.name)
    .sort();

  const entries: AppEntry[] = [];

  for (const appName of appDirs) {
    await page.goto(`/${appName}/`);
    await page.waitForTimeout(500);

    const screenshotPath = path.join(APPS_DIR, appName, "screenshot.png");
    await page.screenshot({ path: screenshotPath, fullPage: false });

    const title = await page.title();
    const description = await page
      .locator('meta[name="description"]')
      .getAttribute("content")
      .catch(() => null);

    entries.push({
      name: appName,
      title: title || appName,
      description: description || "",
      screenshot: `apps/${appName}/screenshot.png`,
    });
  }

  const count = `${entries.length} app${entries.length === 1 ? "" : "s"}`;

  // --- DIRECTORY.md ---
  let md = "# App Directory\n\n";
  md += `> Auto-generated by \`npm run directory\`. ${count}.\n\n`;
  for (const entry of entries) {
    md += `## ${entry.title}\n\n`;
    md += `[\`apps/${entry.name}/\`](apps/${entry.name}/)\n\n`;
    if (entry.description) md += `${entry.description}\n\n`;
    md += `![${entry.title}](${entry.screenshot})\n\n---\n\n`;
  }
  fs.writeFileSync(path.join(ROOT, "DIRECTORY.md"), md.trimEnd() + "\n");

  // --- DIRECTORY.html ---
  const cards = entries
    .map(
      (entry) => `
      <a href="apps/${entry.name}/" class="card">
        <img src="${entry.screenshot}" alt="${entry.title}">
        <div class="card-body">
          <h2>${entry.title}</h2>
          ${entry.description ? `<p>${entry.description}</p>` : ""}
        </div>
      </a>`
    )
    .join("\n");

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>App Directory</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
    background: #f5f5f5;
    color: #222;
    padding: 2rem;
    max-width: 1200px;
    margin: 0 auto;
  }
  h1 { font-size: 1.8rem; margin-bottom: 0.25rem; }
  .subtitle { color: #666; margin-bottom: 2rem; font-size: 0.95rem; }
  .grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(340px, 1fr));
    gap: 1.5rem;
  }
  .card {
    background: #fff;
    border-radius: 10px;
    overflow: hidden;
    box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    transition: transform 0.15s, box-shadow 0.15s;
    text-decoration: none;
    color: inherit;
    display: block;
  }
  .card:hover {
    transform: translateY(-2px);
    box-shadow: 0 4px 12px rgba(0,0,0,0.15);
  }
  .card img {
    width: 100%;
    height: 220px;
    object-fit: cover;
    object-position: top;
    border-bottom: 1px solid #eee;
  }
  .card-body { padding: 1rem 1.25rem; }
  .card-body h2 { font-size: 1.1rem; margin-bottom: 0.35rem; }
  .card-body p { font-size: 0.9rem; color: #555; line-height: 1.4; }
</style>
</head>
<body>
  <h1>App Directory</h1>
  <p class="subtitle">${count}</p>
  <div class="grid">
${cards}
  </div>
</body>
</html>
`;
  fs.writeFileSync(path.join(ROOT, "DIRECTORY.html"), html);

  console.log(`Wrote DIRECTORY.md and DIRECTORY.html with ${entries.length} app(s)`);
});
